#!/usr/bin/env bash

readonly PLATFORM="Darwin-Power Macintosh"

echo "Running for $PLATFORM" >&2

if test "x${PACKAGE_ROOT_DIR:-notset}" == "xnotset"
then
    echo "This program must be run in a chestnut package. Dying" >&2
    exit 1
fi      

language="$1"
if test "x$language" == "x"
then
    echo "Please specify a language as a command line argument" >&2
    exit 1
fi

echo "Current PACKAGE_ROOT_DIR is $PACKAGE_ROOT_DIR" >&2
hello_translations="$PACKAGE_ROOT_DIR/Resources/$PLATFORM/hello_translations"

salutation=`cat "$hello_translations" | grep -e "^$language" | cut -d':' -f 2-`
echo "$salutation"

exit 0
